import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { AuthProvider } from '@/context/AuthContext';
import ReduxProvider from '@/store/redux-provider';
import { Toaster } from 'react-hot-toast';
import CarbonWrapper from '@/components/common/CarbonWrapper';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'squareyourcircles',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <AuthProvider>
            <CarbonWrapper>
              <Toaster position="top-right" />
              {children}
            </CarbonWrapper>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
