import BackgroundMark from '@/components/common/BackgroundMark';
import CarbonWrapper from '@/components/common/CarbonWrapper';
import { AuthProvider } from '@/context/AuthContext';
import { MarkProvider } from '@/context/MarkContext';
import ReduxProvider from '@/store/redux-provider';
import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'squareyourcircles',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ReduxProvider>
          <AuthProvider>
            <MarkProvider initialVariant="background" initialThreshold={10}>
              <CarbonWrapper>
                <BackgroundMark />
                <Toaster position="top-right" />
                {children}
              </CarbonWrapper>
            </MarkProvider>
          </AuthProvider>
        </ReduxProvider>
      </body>
    </html>
  );
}
